FC = $.fullCalendar
# a reference to FullCalendar's root namespace
View = FC.views.month
# the class that all views must inherit from
CustomView = undefined
# our subclass
CustomView = View.extend(
  # initialize: ->
  #   # called once when the view is instantiated, when the user switches to the view.
  #   # initialize member variables or do other setup tasks.
  #   return
  # render: ->
  #   # responsible for displaying the skeleton of the view within the already-defined
  #   # this.el, a jQuery element.
  #   return
  # setHeight: (height, isAuto) ->
  #   # responsible for adjusting the pixel-height of the view. if isAuto is true, the
  #   # view may be its natural height, and `height` becomes merely a suggestion.
  #   return

  renderHtml: ->
    '<div class="hidden">' + @dayGrid.headHtml() + '<div class="fc-day-grid-container"><div class="fc-day-grid"/></div></div>'


  # renderEvents: (events) ->
  #   @dayGrid.renderEvents events
  #   @updateHeight()
  # # #   # must compensate for events that overflow the row
  #   return

  renderEvents: (events) ->
    $('#calendar-list ul').html('')
    $.each events, (index, event)->
      console.log JSON.stringify(event)
      $('#calendar-list ul').append $(
        "<li>
          <a href='#{event.url}'></a>
          <div class='calendar-event'>
            <div class='event-img #{event.className.join(' ')}'>
              <img src='#{event.image_url}' alt='#{event.title}'>
            </div>
            <div class='event-date'>
              <span>#{event.event_date}</span>
            </div>
            <div class='event-title'>
              <span>#{event.title}</span>
            </div>
            <div class='event-address'>
              <span>#{event.address}</span>
            </div>
          </div>
        </li>"
      )
    return

  destroyEvents: ->
  #   # responsible for undoing everything in renderEvents
  #   return
  # renderSelection: (range) ->
  #   # accepts a {start,end} object made of Moments, and must render the selection
  #   return
  # destroySelection: ->
  #   # responsible for undoing everything in renderSelection
  #   return
)
FC.views.custom = CustomView
# register our class with the view system

# ---
# generated by js2coffee 2.1.0



# FC = $.fullCalendar
# # a reference to FullCalendar's root namespace
# View = FC.views.month
# # the class that all views must inherit from
# CustomView = undefined
# # our subclass
# CustomView = View.extend({})
# FC.views.custom = CustomView
# # register our class with the view system
#
# # ---
# # generated by js2coffee 2.1.0
